package vista;

import CRUD.MinutaPP;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Minuta;

/**
 *
 * @author diego
 */
public class Form_Minuta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Minuta.class.getName());

    /**
     * Creates new form Form_Minuta
     */
    public Form_Minuta() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    public void limpiar() {
        this.jtxt_idMinuta.setText("");
        this.jtxt_idMinuta.setEnabled(true);

        this.jcmb_tipo.setSelectedIndex(0); // DIARIA o MENSUAL

        this.jtxt_dia.setText("");
        this.jtxt_mes.setText("");
        this.jtxt_agnio.setText("");

        this.jtxt_nombre.setText("");
        this.jtxt_descripcion.setText("");

        this.jtxt_idMinuta.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpan_Opciones = new javax.swing.JPanel();
        jtbtn_agregar = new javax.swing.JButton();
        jbtn_Actualizar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_listar = new javax.swing.JButton();
        jbtn_Buscar = new javax.swing.JButton();
        jbtn_Limpiar = new javax.swing.JButton();
        jbtn_Volver = new javax.swing.JButton();
        jbtn_Salir = new javax.swing.JButton();
        jbtn_verDetalleMinuta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jpan_InfoGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_idMinuta = new javax.swing.JTextField();
        jtxt_descripcion = new javax.swing.JTextField();
        jtxt_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_dia = new javax.swing.JTextField();
        jtxt_mes = new javax.swing.JTextField();
        jtxt_agnio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jcmb_tipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_datos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpan_Opciones.setBackground(new java.awt.Color(248, 246, 231));

        jtbtn_agregar.setBackground(new java.awt.Color(204, 215, 198));
        jtbtn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbtn_agregar.setText("Agregar");
        jtbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_agregarActionPerformed(evt);
            }
        });

        jbtn_Actualizar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Actualizar.setText("Actualizar");
        jbtn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ActualizarActionPerformed(evt);
            }
        });

        jbtn_eliminar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jbtn_listar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_listar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_listar.setText("Listar");
        jbtn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarActionPerformed(evt);
            }
        });

        jbtn_Buscar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Buscar.setText("Buscar");
        jbtn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_BuscarActionPerformed(evt);
            }
        });

        jbtn_Limpiar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Limpiar.setText("Limpiar");
        jbtn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_LimpiarActionPerformed(evt);
            }
        });

        jbtn_Volver.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Volver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Volver.setText("Volver");
        jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_VolverActionPerformed(evt);
            }
        });

        jbtn_Salir.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Salir.setText("Salir");
        jbtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SalirActionPerformed(evt);
            }
        });

        jbtn_verDetalleMinuta.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_verDetalleMinuta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_verDetalleMinuta.setText("Ver detalle");
        jbtn_verDetalleMinuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_verDetalleMinutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpan_OpcionesLayout = new javax.swing.GroupLayout(jpan_Opciones);
        jpan_Opciones.setLayout(jpan_OpcionesLayout);
        jpan_OpcionesLayout.setHorizontalGroup(
            jpan_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_OpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtn_agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_verDetalleMinuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpan_OpcionesLayout.setVerticalGroup(
            jpan_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_OpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jbtn_verDetalleMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cocinero.png"))); // NOI18N
        jLabel13.setText("BIFUD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jpan_InfoGeneral.setBackground(new java.awt.Color(204, 215, 198));
        jpan_InfoGeneral.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Minuta:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");

        jtxt_idMinuta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_idMinutaFocusLost(evt);
            }
        });
        jtxt_idMinuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_idMinutaMousePressed(evt);
            }
        });
        jtxt_idMinuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idMinutaActionPerformed(evt);
            }
        });

        jtxt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("/");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("/");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha inicio: ");

        jtxt_dia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_diaFocusLost(evt);
            }
        });
        jtxt_dia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_diaMousePressed(evt);
            }
        });
        jtxt_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_diaActionPerformed(evt);
            }
        });

        jtxt_mes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_mesFocusLost(evt);
            }
        });
        jtxt_mes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_mesMousePressed(evt);
            }
        });
        jtxt_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mesActionPerformed(evt);
            }
        });

        jtxt_agnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_agnioFocusLost(evt);
            }
        });
        jtxt_agnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_agnioMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Información general");

        jcmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diaria", "Semanal", "Mensual", " " }));
        jcmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpan_InfoGeneralLayout = new javax.swing.GroupLayout(jpan_InfoGeneral);
        jpan_InfoGeneral.setLayout(jpan_InfoGeneralLayout);
        jpan_InfoGeneralLayout.setHorizontalGroup(
            jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15))
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jtxt_idMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(19, 19, 19)
                                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                        .addComponent(jtxt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_agnio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(35, 35, 35)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jtxt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(125, 125, 125))
        );
        jpan_InfoGeneralLayout.setVerticalGroup(
            jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(34, 34, 34)
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_idMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jtxt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxt_agnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel7))))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jtbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Tipo", "Fecha", "Nombre", "Descripcion"
            }
        ));
        jtbl_datos.setMaximumSize(new java.awt.Dimension(1180, 80));
        jScrollPane1.setViewportView(jtbl_datos);

        jPanel1.setBackground(new java.awt.Color(248, 246, 231));

        jLabel14.setBackground(new java.awt.Color(204, 215, 198));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(115, 196, 173));
        jLabel14.setText("Administracion de Minutas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpan_Opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpan_InfoGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpan_InfoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpan_Opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_agregarActionPerformed
        int idMinuta = 0;
        String tipo, nombre, descripcion;
        String dia, mes, agnio, fechaStr;
        Date fecha = null;

        try {
            idMinuta = Integer.parseInt(this.jtxt_idMinuta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jtxt_idMinuta.requestFocus();
            return;
        }

        tipo = this.jcmb_tipo.getSelectedItem().toString();
        nombre = this.jtxt_nombre.getText();
        descripcion = this.jtxt_descripcion.getText();

        dia = this.jtxt_dia.getText();
        mes = this.jtxt_mes.getText();
        agnio = this.jtxt_agnio.getText();

        if (nombre.isEmpty() || descripcion.isEmpty() || dia.isEmpty() || mes.isEmpty() || agnio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos obligatorios", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        fechaStr = dia + "/" + mes + "/" + agnio;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        formato.setLenient(false);

        try {
            fecha = formato.parse(fechaStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Fecha inválida (dd/MM/aaaa)", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jtxt_dia.requestFocus();
            return;
        }

        Minuta minuta = new Minuta();
        minuta.setIdMinuta(idMinuta);
        minuta.setTipo(tipo);
        minuta.setNombre(nombre);
        minuta.setDescripcion(descripcion);
        minuta.setFecha(fecha);

        MinutaPP reg = new MinutaPP();

        if (reg.insertar(minuta)) {
            JOptionPane.showMessageDialog(this, "Minuta agregada correctamente", "Ingreso Minuta", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar la minuta", "Ingreso Minuta", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jtbtn_agregarActionPerformed

    private void jbtn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ActualizarActionPerformed

        int idMinuta = 0;
        String tipo, nombre, descripcion;
        String dia, mes, agnio, fechaStr;
        Date fecha = null;

        try {
            idMinuta = Integer.parseInt(this.jtxt_idMinuta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jtxt_idMinuta.requestFocus();
            return;
        }

        tipo = this.jcmb_tipo.getSelectedItem().toString();
        nombre = this.jtxt_nombre.getText();
        descripcion = this.jtxt_descripcion.getText();

        dia = this.jtxt_dia.getText();
        mes = this.jtxt_mes.getText();
        agnio = this.jtxt_agnio.getText();

        if (nombre.isEmpty() || descripcion.isEmpty() || dia.isEmpty() || mes.isEmpty() || agnio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos obligatorios", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        fechaStr = dia + "/" + mes + "/" + agnio;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        formato.setLenient(false);

        try {
            fecha = formato.parse(fechaStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Fecha inválida (dd/MM/aaaa)", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jtxt_dia.requestFocus();
            return;
        }

        Minuta minuta = new Minuta();
        minuta.setIdMinuta(idMinuta);
        minuta.setTipo(tipo);
        minuta.setNombre(nombre);
        minuta.setDescripcion(descripcion);
        minuta.setFecha(fecha);

        MinutaPP reg = new MinutaPP();

        if (reg.actualizar(minuta)) {
            JOptionPane.showMessageDialog(this, "Minuta actualizada correctamente", "Actualización", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar la minuta", "Actualización", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtn_ActualizarActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed

        String idTexto = this.jtxt_idMinuta.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un ID para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar?", "Aviso", 1);

        if (opcion == JOptionPane.YES_OPTION) {
            int idMinuta;
            try {
                idMinuta = Integer.parseInt(idTexto);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID inválido", "Validación", JOptionPane.WARNING_MESSAGE);
                this.jtxt_idMinuta.requestFocus();
                return;
            }

            MinutaPP reg = new MinutaPP();
            boolean eliminado = reg.eliminar(idMinuta);

            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Minuta eliminada correctamente", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
                this.limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la minuta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Minuta NO eliminada", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jbtn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarActionPerformed

        MinutaPP reg = new MinutaPP();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_datos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        List<Minuta> lista = reg.listar();

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        for (Minuta m : lista) {
            modelo.addRow(new Object[]{
                m.getIdMinuta(),
                m.getTipo(),
                m.getNombre(),
                m.getDescripcion(),
                m.getFecha() != null ? formato.format(m.getFecha()) : ""
            });
        }
    }//GEN-LAST:event_jbtn_listarActionPerformed

    private void jbtn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_BuscarActionPerformed

        String idTexto = this.jtxt_idMinuta.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un ID para buscar", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idMinuta;
        try {
            idMinuta = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jtxt_idMinuta.requestFocus();
            return;
        }

        MinutaPP reg = new MinutaPP();
        Minuta minuta = reg.buscarPorId(idMinuta);

        if (minuta != null) {
            this.jtxt_idMinuta.setText(String.valueOf(minuta.getIdMinuta()));
            this.jtxt_idMinuta.setEnabled(false);

            this.jcmb_tipo.setSelectedItem(minuta.getTipo());
            this.jtxt_nombre.setText(minuta.getNombre());
            this.jtxt_descripcion.setText(minuta.getDescripcion());

            Date fecha = minuta.getFecha();
            Calendar cal = Calendar.getInstance();
            cal.setTime(fecha);
            this.jtxt_dia.setText(String.valueOf(cal.get(Calendar.DAY_OF_MONTH)));
            this.jtxt_mes.setText(String.valueOf(cal.get(Calendar.MONTH) + 1));
            this.jtxt_agnio.setText(String.valueOf(cal.get(Calendar.YEAR)));
        } else {
            JOptionPane.showMessageDialog(this, "Minuta no encontrada", "Buscar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_BuscarActionPerformed

    private void jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_VolverActionPerformed
        Form_MenuPrincipal menu = new Form_MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_VolverActionPerformed

    private void jbtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtn_SalirActionPerformed

    private void jtxt_idMinutaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_idMinutaFocusLost

    }//GEN-LAST:event_jtxt_idMinutaFocusLost

    private void jtxt_idMinutaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_idMinutaMousePressed

    }//GEN-LAST:event_jtxt_idMinutaMousePressed

    private void jtxt_idMinutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idMinutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idMinutaActionPerformed

    private void jtxt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreActionPerformed

    private void jtxt_diaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_diaFocusLost
        if (jtxt_dia.getText().trim().isEmpty()) {
            jtxt_dia.setText("01");
            jtxt_dia.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jtxt_diaFocusLost

    private void jtxt_diaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_diaMousePressed
        if (jtxt_dia.getText().equals("01")) {
            jtxt_dia.setText("");
            jtxt_dia.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtxt_diaMousePressed

    private void jtxt_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_diaActionPerformed

    private void jtxt_mesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_mesFocusLost
        if (jtxt_mes.getText().trim().isEmpty()) {
            jtxt_mes.setText("02");
            jtxt_mes.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jtxt_mesFocusLost

    private void jtxt_mesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_mesMousePressed
        if (jtxt_mes.getText().equals("02")) {
            jtxt_mes.setText("");
            jtxt_mes.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtxt_mesMousePressed

    private void jtxt_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mesActionPerformed

    private void jtxt_agnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_agnioFocusLost
        if (jtxt_agnio.getText().trim().isEmpty()) {
            jtxt_agnio.setText("3333");
            jtxt_agnio.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jtxt_agnioFocusLost

    private void jtxt_agnioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_agnioMousePressed
        if (jtxt_agnio.getText().equals("3333")) {
            jtxt_agnio.setText("");
            jtxt_agnio.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtxt_agnioMousePressed

    private void jcmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_tipoActionPerformed

    private void jbtn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_LimpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jbtn_LimpiarActionPerformed

    private void jbtn_verDetalleMinutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_verDetalleMinutaActionPerformed
        From_MinutaDetalle menu = new From_MinutaDetalle();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_verDetalleMinutaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Form_Minuta().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Actualizar;
    private javax.swing.JButton jbtn_Buscar;
    private javax.swing.JButton jbtn_Limpiar;
    private javax.swing.JButton jbtn_Salir;
    private javax.swing.JButton jbtn_Volver;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JButton jbtn_verDetalleMinuta;
    private javax.swing.JComboBox<String> jcmb_tipo;
    private javax.swing.JPanel jpan_InfoGeneral;
    private javax.swing.JPanel jpan_Opciones;
    private javax.swing.JTable jtbl_datos;
    private javax.swing.JButton jtbtn_agregar;
    private javax.swing.JTextField jtxt_agnio;
    private javax.swing.JTextField jtxt_descripcion;
    private javax.swing.JTextField jtxt_dia;
    private javax.swing.JTextField jtxt_idMinuta;
    private javax.swing.JTextField jtxt_mes;
    private javax.swing.JTextField jtxt_nombre;
    // End of variables declaration//GEN-END:variables
}
