/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import CRUD.MinutaDetalleIngredientesPP;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Minuta;
import modelo.MinutaDetalle;
import modelo.MinutaDetalleIngredientes;

/**
 *
 * @author diego
 */
public class Form_DetalleIngrediente extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_DetalleIngrediente.class.getName());

    /**
     * Creates new form Form_DetalleIngrediente
     */
    public Form_DetalleIngrediente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void limpiar() {
        jtxt_idMinuta.setText("");
        jtxt_idDetalle.setText("");
        jtxt_idIngrediente.setText("");
        jtxt_cantidad.setText("");
        jcmb_unidadMedida.setSelectedIndex(0);
        jtxt_idIngrediente.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_datos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jpan_Opciones = new javax.swing.JPanel();
        jtbtn_agregar = new javax.swing.JButton();
        jbtn_Actualizar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_listar = new javax.swing.JButton();
        jbtn_Buscar = new javax.swing.JButton();
        jbtn_Limpiar = new javax.swing.JButton();
        jbtn_Volver = new javax.swing.JButton();
        jbtn_Salir = new javax.swing.JButton();
        jpan_InfoGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_idMinuta = new javax.swing.JTextField();
        jtxt_cantidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jcmb_unidadMedida = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtxt_idDetalle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_idIngrediente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Minuta", "ID Detalle", "ID Ingrediente", "Cantidad", "Unidad de medida"
            }
        ));
        jtbl_datos.setMaximumSize(new java.awt.Dimension(1180, 80));
        jScrollPane1.setViewportView(jtbl_datos);

        jPanel1.setBackground(new java.awt.Color(248, 246, 231));

        jLabel14.setBackground(new java.awt.Color(204, 215, 198));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(115, 196, 173));
        jLabel14.setText("Administracion de Ingredientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cocinero.png"))); // NOI18N
        jLabel13.setText("BIFUD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jpan_Opciones.setBackground(new java.awt.Color(248, 246, 231));

        jtbtn_agregar.setBackground(new java.awt.Color(204, 215, 198));
        jtbtn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbtn_agregar.setText("Agregar");
        jtbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_agregarActionPerformed(evt);
            }
        });

        jbtn_Actualizar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Actualizar.setText("Actualizar");
        jbtn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ActualizarActionPerformed(evt);
            }
        });

        jbtn_eliminar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jbtn_listar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_listar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_listar.setText("Listar");
        jbtn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarActionPerformed(evt);
            }
        });

        jbtn_Buscar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Buscar.setText("Buscar");
        jbtn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_BuscarActionPerformed(evt);
            }
        });

        jbtn_Limpiar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Limpiar.setText("Limpiar");
        jbtn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_LimpiarActionPerformed(evt);
            }
        });

        jbtn_Volver.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Volver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Volver.setText("Volver");
        jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_VolverActionPerformed(evt);
            }
        });

        jbtn_Salir.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Salir.setText("Salir");
        jbtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpan_OpcionesLayout = new javax.swing.GroupLayout(jpan_Opciones);
        jpan_Opciones.setLayout(jpan_OpcionesLayout);
        jpan_OpcionesLayout.setHorizontalGroup(
            jpan_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_OpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtn_agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpan_OpcionesLayout.setVerticalGroup(
            jpan_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_OpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpan_InfoGeneral.setBackground(new java.awt.Color(204, 215, 198));
        jpan_InfoGeneral.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Minuta:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Unidad de medida:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad:");

        jtxt_idMinuta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_idMinutaFocusLost(evt);
            }
        });
        jtxt_idMinuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_idMinutaMousePressed(evt);
            }
        });
        jtxt_idMinuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idMinutaActionPerformed(evt);
            }
        });

        jtxt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cantidadActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Información general");

        jcmb_unidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gramo", "Kilogramo", "Mililitro ", "Litro", "Unidad", " " }));
        jcmb_unidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_unidadMedidaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Detalle:");

        jtxt_idDetalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_idDetalleFocusLost(evt);
            }
        });
        jtxt_idDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_idDetalleMousePressed(evt);
            }
        });
        jtxt_idDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idDetalleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID ingrediente:");

        jtxt_idIngrediente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_idIngredienteFocusLost(evt);
            }
        });
        jtxt_idIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_idIngredienteMousePressed(evt);
            }
        });
        jtxt_idIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpan_InfoGeneralLayout = new javax.swing.GroupLayout(jpan_InfoGeneral);
        jpan_InfoGeneral.setLayout(jpan_InfoGeneralLayout);
        jpan_InfoGeneralLayout.setHorizontalGroup(
            jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jtxt_idIngrediente))
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jtxt_idMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jtxt_idDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jcmb_unidadMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(46, 805, Short.MAX_VALUE))
        );
        jpan_InfoGeneralLayout.setVerticalGroup(
            jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(34, 34, 34)
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcmb_unidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxt_idMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxt_idDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxt_idIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpan_Opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpan_InfoGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpan_InfoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpan_Opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_agregarActionPerformed

        try {

            int idIngrediente = Integer.parseInt(this.jtxt_idIngrediente.getText().trim());
            int idMinuta = Integer.parseInt(this.jtxt_idMinuta.getText().trim());
            int idDetalle = Integer.parseInt(this.jtxt_idDetalle.getText().trim());
            double cantidad = Double.parseDouble(this.jtxt_cantidad.getText().trim());
            String unidad = this.jcmb_unidadMedida.getSelectedItem().toString();

            if (unidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecciona una unidad de medida", "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Minuta m = new Minuta();
            m.setIdMinuta(idMinuta);

            MinutaDetalle d = new MinutaDetalle();
            d.setIdDetalle(idDetalle);

            MinutaDetalleIngredientes mdi = new MinutaDetalleIngredientes(m, d, idIngrediente, cantidad, unidad);

            MinutaDetalleIngredientesPP reg = new MinutaDetalleIngredientesPP();
            if (reg.insertar(mdi)) {
                JOptionPane.showMessageDialog(this, "Ingrediente agregado correctamente", "Agregar", JOptionPane.INFORMATION_MESSAGE);
                this.limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar el ingrediente", "Agregar", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifica que los campos numéricos sean válidos", "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtbtn_agregarActionPerformed

    private void jbtn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ActualizarActionPerformed

        try {
            int idIngrediente = Integer.parseInt(this.jtxt_idIngrediente.getText().trim());
            int idMinuta = Integer.parseInt(this.jtxt_idMinuta.getText().trim());
            int idDetalle = Integer.parseInt(this.jtxt_idDetalle.getText().trim());
            double cantidad = Double.parseDouble(this.jtxt_cantidad.getText().trim());
            String unidad = this.jcmb_unidadMedida.getSelectedItem().toString();

            if (unidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecciona una unidad de medida", "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Creamos los objetos Minuta y MinutaDetalle
            Minuta m = new Minuta();
            m.setIdMinuta(idMinuta);

            MinutaDetalle d = new MinutaDetalle();
            d.setIdDetalle(idDetalle);

            // Creamos el objeto principal con todos los datos
            MinutaDetalleIngredientes mdi = new MinutaDetalleIngredientes();
            mdi.setIdIngrediente(idIngrediente);
            mdi.setIdMinuta(m);
            mdi.setIdDetalle(d);
            mdi.setCantidad(cantidad);
            mdi.setUnidadMedida(unidad);

            // Llamamos al DAO
            MinutaDetalleIngredientesPP reg = new MinutaDetalleIngredientesPP();
            if (reg.actualizar(mdi)) {
                JOptionPane.showMessageDialog(this, "Ingrediente actualizado correctamente", "Actualización", JOptionPane.INFORMATION_MESSAGE);
                this.limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el ingrediente", "Actualización", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifica que los campos numéricos sean válidos", "Validación", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jbtn_ActualizarActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        String idDetalleStr = jtxt_idDetalle.getText().trim();

        if (idDetalleStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el ID del detalle a eliminar", "Validación", JOptionPane.WARNING_MESSAGE);
            jtxt_idDetalle.requestFocus();
            return;
        }

        int idDetalle = 0;

        try {
            idDetalle = Integer.parseInt(idDetalleStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Detalle inválido", "Validación", JOptionPane.WARNING_MESSAGE);
            jtxt_idDetalle.requestFocus();
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Eliminar registro con ID Detalle " + idDetalle + "?",
                "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        MinutaDetalleIngredientesPP pp = new MinutaDetalleIngredientesPP();

        if (pp.eliminar(idDetalle)) {
            JOptionPane.showMessageDialog(this, "Ingrediente eliminado correctamente", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el ingrediente", "Eliminar", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jbtn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarActionPerformed
        MinutaDetalleIngredientesPP pp = new MinutaDetalleIngredientesPP();
        List<MinutaDetalleIngredientes> lista = pp.listarTodos(); // usar listarTodos()

        DefaultTableModel modelo = (DefaultTableModel) jtbl_datos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (MinutaDetalleIngredientes mdi : lista) {
            Object[] fila = new Object[5];
            fila[0] = (mdi.getIdMinuta() != null) ? mdi.getIdMinuta().getIdMinuta() : "";
            fila[1] = (mdi.getIdDetalle() != null) ? mdi.getIdDetalle().getIdDetalle() : "";
            fila[2] = mdi.getIdIngrediente();
            fila[3] = mdi.getCantidad();
            fila[4] = mdi.getUnidadMedida();
            modelo.addRow(fila);
        }

        JOptionPane.showMessageDialog(this,
                "Se listaron " + lista.size() + " ingredientes",
                "Listar", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jbtn_listarActionPerformed

    private void jbtn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_BuscarActionPerformed
        {
            String idIngredienteStr = jtxt_idIngrediente.getText().trim();
            String idMinutaStr = jtxt_idMinuta.getText().trim();
            String idDetalleStr = jtxt_idDetalle.getText().trim();

            int camposUsados = 0;
            if (!idIngredienteStr.isEmpty()) {
                camposUsados++;
            }
            if (!idMinutaStr.isEmpty()) {
                camposUsados++;
            }
            if (!idDetalleStr.isEmpty()) {
                camposUsados++;
            }

            if (camposUsados == 0) {
                JOptionPane.showMessageDialog(this, "Ingresa al menos un campo para buscar", "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (camposUsados > 1) {
                JOptionPane.showMessageDialog(this, "Solo se permite buscar por un campo a la vez", "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            MinutaDetalleIngredientesPP pp = new MinutaDetalleIngredientesPP();
            if (!idIngredienteStr.isEmpty()) {
                try {
                    int idIngrediente = Integer.parseInt(idIngredienteStr);
                    MinutaDetalleIngredientes mdi = pp.buscarPorIdDetalle(idIngrediente);
                    if (mdi != null) {
                        jtxt_idMinuta.setText(String.valueOf(mdi.getIdMinuta().getIdMinuta()));
                        jtxt_idDetalle.setText(String.valueOf(mdi.getIdDetalle().getIdDetalle()));
                        jtxt_cantidad.setText(String.valueOf(mdi.getCantidad()));
                        jcmb_unidadMedida.setSelectedItem(mdi.getUnidadMedida());
                        JOptionPane.showMessageDialog(this, "Ingrediente encontrado", "Buscar", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Ingrediente no encontrado", "Buscar", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "ID Ingrediente inválido", "Validación", JOptionPane.WARNING_MESSAGE);
                }
                return;
            }

            if (!idMinutaStr.isEmpty()) {
                try {
                    int idMinuta = Integer.parseInt(idMinutaStr);
                    List<MinutaDetalleIngredientes> lista = (List<MinutaDetalleIngredientes>) pp.buscarPorIdDetalle(idMinuta); // usar listarPorMinuta
                    JOptionPane.showMessageDialog(this, "Se encontraron " + lista.size() + " ingredientes", "Buscar", JOptionPane.INFORMATION_MESSAGE);
                    // Aquí podrías llenar la tabla con los resultados
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "ID Minuta inválido", "Validación", JOptionPane.WARNING_MESSAGE);
                }
                return;
            }

            if (!idDetalleStr.isEmpty()) {
                try {
                    int idDetalle = Integer.parseInt(idDetalleStr);
                    List<MinutaDetalleIngredientes> lista = (List<MinutaDetalleIngredientes>) pp.buscarPorIdDetalle(idDetalle); // usar listarPorDetalle
                    JOptionPane.showMessageDialog(this, "Se encontraron " + lista.size() + " ingredientes", "Buscar", JOptionPane.INFORMATION_MESSAGE);
                    // Aquí también podrías llenar la tabla con los resultados
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "ID Detalle inválido", "Validación", JOptionPane.WARNING_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_jbtn_BuscarActionPerformed

    private void jbtn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_LimpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jbtn_LimpiarActionPerformed

    private void jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_VolverActionPerformed
        From_MinutaDetalle menu = new From_MinutaDetalle();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtn_VolverActionPerformed

    private void jbtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtn_SalirActionPerformed

    private void jtxt_idMinutaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_idMinutaFocusLost

    }//GEN-LAST:event_jtxt_idMinutaFocusLost

    private void jtxt_idMinutaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_idMinutaMousePressed

    }//GEN-LAST:event_jtxt_idMinutaMousePressed

    private void jtxt_idMinutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idMinutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idMinutaActionPerformed

    private void jtxt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cantidadActionPerformed

    private void jcmb_unidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_unidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_unidadMedidaActionPerformed

    private void jtxt_idDetalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_idDetalleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idDetalleFocusLost

    private void jtxt_idDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_idDetalleMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idDetalleMousePressed

    private void jtxt_idDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idDetalleActionPerformed

    private void jtxt_idIngredienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_idIngredienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idIngredienteFocusLost

    private void jtxt_idIngredienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_idIngredienteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idIngredienteMousePressed

    private void jtxt_idIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Form_DetalleIngrediente().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Actualizar;
    private javax.swing.JButton jbtn_Buscar;
    private javax.swing.JButton jbtn_Limpiar;
    private javax.swing.JButton jbtn_Salir;
    private javax.swing.JButton jbtn_Volver;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JComboBox<String> jcmb_unidadMedida;
    private javax.swing.JPanel jpan_InfoGeneral;
    private javax.swing.JPanel jpan_Opciones;
    private javax.swing.JTable jtbl_datos;
    private javax.swing.JButton jtbtn_agregar;
    private javax.swing.JTextField jtxt_cantidad;
    private javax.swing.JTextField jtxt_idDetalle;
    private javax.swing.JTextField jtxt_idIngrediente;
    private javax.swing.JTextField jtxt_idMinuta;
    // End of variables declaration//GEN-END:variables
}
