/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author k-ort
 */
public class Form_MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_MenuPrincipal.class.getName());

    /**
     * Creates new form From_MenuPrincipal
     */
    public Form_MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn_Empresa = new javax.swing.JButton();
        jbtn_Personal = new javax.swing.JButton();
        jbtn_Recetas = new javax.swing.JButton();
        jbtn_InventarioConsumibles = new javax.swing.JButton();
        jbtn_InventarioActivos = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jbtn_Salir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(164, 201, 223));

        jbtn_Empresa.setBackground(new java.awt.Color(123, 183, 209));
        jbtn_Empresa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbtn_Empresa.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Empresa.setText("Empresa");
        jbtn_Empresa.setBorder(null);
        jbtn_Empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_EmpresaMouseEntered(evt);
            }
        });
        jbtn_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_EmpresaActionPerformed(evt);
            }
        });

        jbtn_Personal.setBackground(new java.awt.Color(123, 183, 209));
        jbtn_Personal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbtn_Personal.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Personal.setText("Personal");
        jbtn_Personal.setBorder(null);
        jbtn_Personal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_PersonalMouseEntered(evt);
            }
        });

        jbtn_Recetas.setBackground(new java.awt.Color(123, 183, 209));
        jbtn_Recetas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbtn_Recetas.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Recetas.setText("Recetas");
        jbtn_Recetas.setBorder(null);
        jbtn_Recetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_RecetasMouseEntered(evt);
            }
        });

        jbtn_InventarioConsumibles.setBackground(new java.awt.Color(123, 183, 209));
        jbtn_InventarioConsumibles.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbtn_InventarioConsumibles.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_InventarioConsumibles.setText("Inventario Consumibles");
        jbtn_InventarioConsumibles.setBorder(null);
        jbtn_InventarioConsumibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_InventarioConsumiblesMouseEntered(evt);
            }
        });

        jbtn_InventarioActivos.setBackground(new java.awt.Color(123, 183, 209));
        jbtn_InventarioActivos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbtn_InventarioActivos.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_InventarioActivos.setText("Inventario de Activos");
        jbtn_InventarioActivos.setBorder(null);
        jbtn_InventarioActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_InventarioActivosMouseEntered(evt);
            }
        });

        Logo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(29, 58, 109));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guantes-de-cocina (1).png"))); // NOI18N
        Logo.setText("BIBFUD");

        jbtn_Salir.setBackground(new java.awt.Color(123, 183, 209));
        jbtn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbtn_Salir.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Salir.setText("Salir");
        jbtn_Salir.setBorder(null);
        jbtn_Salir.setPreferredSize(new java.awt.Dimension(162, 22));
        jbtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtn_InventarioActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtn_InventarioConsumibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtn_Recetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtn_Personal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtn_Empresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jbtn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jbtn_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtn_Personal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtn_Recetas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtn_InventarioConsumibles, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtn_InventarioActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        jPanel3.setBackground(new java.awt.Color(214, 228, 245));

        jPanel2.setBackground(new java.awt.Color(164, 201, 223));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administracion de base de datos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 58, 109));
        jLabel3.setText("Bienvenido al Sistema de Gestión");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 58, 109));
        jLabel4.setText("Selecciona una opción del menú lateral para comenzar.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 58, 109));
        jLabel5.setText("Aquí podrás administrar los distintos módulos del sistema, como:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 58, 109));
        jLabel6.setText("<html> <div style='text-align:left;'> -Empresas registradas<br><br>-Personal por contrato y honorarios<br><br> -Activos y consumibles<br><br> -Recetas o registros asociados<br><br> Selecciona un módulo del menú izquierdo para comenzar a trabajar con la información.  Podrás <b>crear</b>, <b>editar</b> o <b>revisar</b> los datos fácilmente desde las opciones del sistema. </div> </html> "); // NOI18N
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_EmpresaActionPerformed
         Form_EmpresaCrud al = new Form_EmpresaCrud();
        al.setVisible(true);
    }//GEN-LAST:event_jbtn_EmpresaActionPerformed

    private void jbtn_EmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_EmpresaMouseEntered
        jbtn_Empresa.setBackground(new Color(74, 160, 196));
    }//GEN-LAST:event_jbtn_EmpresaMouseEntered

    private void jbtn_PersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_PersonalMouseEntered
       jbtn_Personal.setBackground(new Color(74, 160, 196));
    }//GEN-LAST:event_jbtn_PersonalMouseEntered

    private void jbtn_RecetasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_RecetasMouseEntered
        jbtn_Recetas.setBackground(new Color(74, 160, 196));
    }//GEN-LAST:event_jbtn_RecetasMouseEntered

    private void jbtn_InventarioConsumiblesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_InventarioConsumiblesMouseEntered
        jbtn_InventarioConsumibles.setBackground(new Color(74, 160, 196));
    }//GEN-LAST:event_jbtn_InventarioConsumiblesMouseEntered

    private void jbtn_InventarioActivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_InventarioActivosMouseEntered
        jbtn_InventarioActivos.setBackground(new Color(74, 160, 196));
    }//GEN-LAST:event_jbtn_InventarioActivosMouseEntered

    private void jbtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtn_SalirActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new From_MenuPrincipal().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtn_Empresa;
    private javax.swing.JButton jbtn_InventarioActivos;
    private javax.swing.JButton jbtn_InventarioConsumibles;
    private javax.swing.JButton jbtn_Personal;
    private javax.swing.JButton jbtn_Recetas;
    private javax.swing.JButton jbtn_Salir;
    // End of variables declaration//GEN-END:variables
}
