/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import CRUD.RegistroPersonalPorContrato;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.PersonalPorContrato;



/**
 *
 * @author ikari
 */
public class RegistroDePersonalPorContrato extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroDePersonalPorContrato.class.getName());

    /**
     * Creates new form RegistroDePersonalPorContrato
     */
    public RegistroDePersonalPorContrato() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtn_Salir = new javax.swing.JButton();
        jbtn_Volver = new javax.swing.JButton();
        jbtn_Actualizar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_Buscar = new javax.swing.JButton();
        jbtn_listar = new javax.swing.JButton();
        jtbtn_agregar = new javax.swing.JButton();
        jpan_InfoGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_Rut = new javax.swing.JTextField();
        jtxt_Nombre = new javax.swing.JTextField();
        jtxt_fonoFijo = new javax.swing.JTextField();
        jtxt_cargo = new javax.swing.JTextField();
        jtxt_direccion = new javax.swing.JTextField();
        jchk_Honorario = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxt_DiaInicio = new javax.swing.JTextField();
        jtxt_mesInicio = new javax.swing.JTextField();
        jtxt_agnoInicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxt_diaTermino = new javax.swing.JTextField();
        jtxt_mesTermino = new javax.swing.JTextField();
        jtxt_agnoTerrmino = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxt_tipoHorario = new javax.swing.JTextField();
        jchk_indefinido = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jtxt_sueldo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_datosPersonal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cocinero.png"))); // NOI18N
        jLabel13.setText("BIFUD");

        jPanel3.setBackground(new java.awt.Color(248, 246, 231));

        jLabel14.setBackground(new java.awt.Color(204, 215, 198));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(115, 196, 173));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Registro de Personal por Contrato");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(248, 246, 231));

        jbtn_Salir.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Salir.setText("Salir");
        jbtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SalirActionPerformed(evt);
            }
        });

        jbtn_Volver.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Volver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Volver.setText("Volver");
        jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_VolverActionPerformed(evt);
            }
        });

        jbtn_Actualizar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Actualizar.setText("Actualizar");
        jbtn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ActualizarActionPerformed(evt);
            }
        });

        jbtn_eliminar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jbtn_Buscar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_Buscar.setText("Buscar");
        jbtn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_BuscarActionPerformed(evt);
            }
        });

        jbtn_listar.setBackground(new java.awt.Color(204, 215, 198));
        jbtn_listar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtn_listar.setText("Listar");
        jbtn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarActionPerformed(evt);
            }
        });

        jtbtn_agregar.setBackground(new java.awt.Color(204, 215, 198));
        jtbtn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbtn_agregar.setText("Agregar");
        jtbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbtn_agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jbtn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Volver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );

        jpan_InfoGeneral.setBackground(new java.awt.Color(204, 215, 198));
        jpan_InfoGeneral.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rut:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fono fijo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cargo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección:");

        jtxt_Rut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_RutFocusLost(evt);
            }
        });
        jtxt_Rut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_RutMousePressed(evt);
            }
        });
        jtxt_Rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_RutActionPerformed(evt);
            }
        });

        jtxt_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cargoActionPerformed(evt);
            }
        });

        jtxt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_direccionActionPerformed(evt);
            }
        });

        jchk_Honorario.setBackground(new java.awt.Color(204, 215, 198));
        jchk_Honorario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jchk_Honorario.setForeground(new java.awt.Color(255, 255, 255));
        jchk_Honorario.setText("Trabajador por Honorario");
        jchk_Honorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchk_HonorarioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha inicio: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("/");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("/");

        jtxt_DiaInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_DiaInicioFocusLost(evt);
            }
        });
        jtxt_DiaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_DiaInicioMousePressed(evt);
            }
        });
        jtxt_DiaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_DiaInicioActionPerformed(evt);
            }
        });

        jtxt_mesInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_mesInicioFocusLost(evt);
            }
        });
        jtxt_mesInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_mesInicioMousePressed(evt);
            }
        });
        jtxt_mesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mesInicioActionPerformed(evt);
            }
        });

        jtxt_agnoInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_agnoInicioFocusLost(evt);
            }
        });
        jtxt_agnoInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxt_agnoInicioMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha termino");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("/");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("/");

        jtxt_diaTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_diaTerminoActionPerformed(evt);
            }
        });

        jtxt_mesTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mesTerminoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Información general");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tipo de Horario:");

        jchk_indefinido.setBackground(new java.awt.Color(204, 215, 198));
        jchk_indefinido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jchk_indefinido.setForeground(new java.awt.Color(255, 255, 255));
        jchk_indefinido.setText("Contrato indefinido");
        jchk_indefinido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchk_indefinidoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Sueldo:");

        javax.swing.GroupLayout jpan_InfoGeneralLayout = new javax.swing.GroupLayout(jpan_InfoGeneral);
        jpan_InfoGeneral.setLayout(jpan_InfoGeneralLayout);
        jpan_InfoGeneralLayout.setHorizontalGroup(
            jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addComponent(jchk_indefinido)
                        .addGap(18, 18, 18)
                        .addComponent(jchk_Honorario)
                        .addGap(749, 749, 749))
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jtxt_DiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_mesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_agnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(45, 45, 45)
                                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxt_Nombre)
                                    .addComponent(jtxt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(42, 42, 42)
                                .addComponent(jtxt_fonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpan_InfoGeneralLayout.createSequentialGroup()
                                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(65, 65, 65))
                                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                        .addComponent(jtxt_diaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_mesTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_agnoTerrmino))
                                    .addComponent(jtxt_cargo)
                                    .addComponent(jtxt_direccion)
                                    .addComponent(jtxt_tipoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(86, 86, 86)
                                .addComponent(jtxt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(150, 150, 150))))
            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpan_InfoGeneralLayout.setVerticalGroup(
            jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxt_fonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxt_DiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jtxt_mesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_agnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchk_Honorario)
                            .addComponent(jchk_indefinido)))
                    .addGroup(jpan_InfoGeneralLayout.createSequentialGroup()
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtxt_tipoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jtxt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpan_InfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtxt_diaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_mesTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jtxt_agnoTerrmino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jtbl_datosPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Fono Fijo", "Fecha Inicio", "Cargo", "Direccion", "Tipo horario", "Sueldo", "Fecha Termino", "Contrato indefinido", "Trabajador por honorario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbl_datosPersonal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpan_InfoGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 1306, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpan_InfoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtn_SalirActionPerformed

    private void jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_VolverActionPerformed
        Form_MenuPrincipal menu = new Form_MenuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtn_VolverActionPerformed

    private void jbtn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ActualizarActionPerformed

    }//GEN-LAST:event_jbtn_ActualizarActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        //obtiene el rut ingresado por el usuario
        
        String rut = jtxt_Rut.getText().trim();

        //inicializar el registro para llamar el metodo
        RegistroPersonalPorContrato reg = new RegistroPersonalPorContrato();

        //devuelve el error si se aprieta borra y no hay rut escrito
        if (rut.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un RUT para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //mensaje que pregunta si quieres, el 1 es mas que nada un indicador tipo de mensaje
        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar?", "Aviso", 1);

        //si o no para borrar y los error
        if (opcion == JOptionPane.YES_OPTION) {
            boolean eliminar = reg.eliminar(rut);
            JOptionPane.showMessageDialog(this, "El personal Eliminada", "Eliminado", 1);
        } else {
            JOptionPane.showMessageDialog(this, "El personal fue NO Eliminada", "Eliminada", 2);
        }
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jbtn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_BuscarActionPerformed
        String rut = this.jtxt_Rut.getText();
        RegistroPersonalPorContrato reg = new RegistroPersonalPorContrato();
        PersonalPorContrato contrato = reg.buscarPorRut(rut);

        if (contrato != null) {
            //este bloquea para que el usuario no edite
            this.jtxt_Rut.setText(contrato.getRut());
            this.jtxt_Rut.setEnabled(false);

            this.jtxt_Nombre.setText(contrato.getNombre());
            this.jtxt_fonoFijo.setText(contrato.getFono());
            this.jtxt_direccion.setText(contrato.getDireccion());

            // Fecha de inicio, tuve que pedir al gpt un calendar para que uniera todo los textos y se dara forma aplica para inicio y termino
            Date fechaInicio = contrato.getFechaDeInicio();
            Calendar cal = Calendar.getInstance();
            cal.setTime(fechaInicio);
            this.jtxt_DiaInicio.setText(String.valueOf(cal.get(Calendar.DAY_OF_MONTH)));
            this.jtxt_mesInicio.setText(String.valueOf(cal.get(Calendar.MONTH) + 1));
            this.jtxt_agnoInicio.setText(String.valueOf(cal.get(Calendar.YEAR)));

            // Contrato indefinido
            this.jchk_indefinido.setSelected(contrato.isContratoIndefinido());

            // Fecha de término si es que aplica
            if (!contrato.isEsIndefinido()&& contrato.getFechaDeTermino() != null) {
                cal.setTime((Date) contrato.getFechaDeTermino());
                this.jtxt_diaTermino.setText(String.valueOf(cal.get(Calendar.DAY_OF_MONTH)));
                this.jtxt_mesTermino.setText(String.valueOf(cal.get(Calendar.MONTH) + 1));
                this.jtxt_agnoTerrmino.setText(String.valueOf(cal.get(Calendar.YEAR)));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Personal no encontrado", "Buscar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_BuscarActionPerformed

    private void jbtn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarActionPerformed
        RegistroPersonalPorContrato reg = new RegistroPersonalPorContrato();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_datosPersonal.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        List<PersonalPorContrato> lista = reg.listarTodos(); // Obtener todo el personal

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        for (PersonalPorContrato cont : lista) {
            modelo.addRow(new Object[]{
                cont.getRut(),
                cont.getNombre(),
                cont.getFono(),
                cont.getDireccion(),
                cont.isContratoIndefinido() ? "Indefinido" : "Definido",
                cont.getFechaDeInicio() != null ? formato.format(cont.getFechaDeInicio()) : "",
                cont.getFechaDeTermino() != null ? formato.format(cont.getFechaDeTermino()) : "",
                cont.isHonorario() ? "Activo" : "Sin funciones",    
            });
        }
    }//GEN-LAST:event_jbtn_listarActionPerformed

    private void jtbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_agregarActionPerformed

        //Aca ingresamos las variables que se deben guardar, copien el formato chiquillos
        String rut, nombre, fonoFijo, direccion;
        String diaIni, mesIni, agnioIni, diaTerm, mesTerm, agnioTerm;
        String fechaIniStr, fechaTermStr;
        Date fechaInicio = null;
        Date fechaTermino = null;
        boolean honorario;
        boolean contratoIndefinido;

        //Capturamos los textos recuerden seguir este formato en los otros casos
        rut = this.jtxt_Rut.getText();
        nombre = this.jtxt_Nombre.getText();
        fonoFijo = this.jtxt_fonoFijo.getText();
        direccion = this.jtxt_direccion.getText();

        diaIni = this.jtxt_DiaInicio.getText();
        mesIni = this.jtxt_mesInicio.getText();
        agnioIni = this.jtxt_agnoInicio.getText();

        diaTerm = this.jtxt_diaTermino.getText();
        mesTerm = this.jtxt_mesTermino.getText();
        agnioTerm = this.jtxt_agnoTerrmino.getText();

        fechaIniStr = diaIni + "/" + mesIni + "/" + agnioIni;

        //Aca realizamos el formato de las fechas
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        // Aca validamos las fechas de inicio y termino
        try {
            fechaInicio = formato.parse(fechaIniStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Fecha de inicio inválida (dd/MM/aaaa)", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jtxt_DiaInicio.requestFocus();
            return; // ← DETIENE el flujo si la fecha es inválida
        }

        contratoIndefinido = this.jchk_indefinido.isSelected();

        //para que no tuviera error si se agregara el indefinido tuve que agregar esto a sql ALTER TABLE empresa MODIFY fecha_termino DATE NULL;
        if (!contratoIndefinido) {
            fechaTermStr = diaTerm + "/" + mesTerm + "/" + agnioTerm;
            try {
                fechaTermino = formato.parse(fechaTermStr);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Fecha de término inválida (dd/MM/aaaa)", "Validación", JOptionPane.WARNING_MESSAGE);
                this.jtxt_diaTermino.requestFocus();
                return;
            }
        } else {
            fechaTermino = null; // no se guarda fecha si es indefinido
        }
        
        
        //aca dejamos listo el booleano
        contratoIndefinido = this.jchk_indefinido.isSelected();

        //aca conectamos el agregar a la clase empresa y a la clase registroEmpresas, ademas de que usamos el metodo de agregar
        PersonalPorContrato contrato = new PersonalPorContrato();
        RegistroPersonalPorContrato reg = new RegistroPersonalPorContrato();

        if (reg.agregarRegistroPersonalPorContrato(contrato)) {
            JOptionPane.showMessageDialog(this, " Personal agregad correctamente", "Ingreso Empresa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, " No se pudo agregar el Personal", "Ingreso Empresa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtbtn_agregarActionPerformed

    private void jtxt_RutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_RutFocusLost
        //muestra el ejemplo en gris
        if (jtxt_Rut.getText().trim().isEmpty()) {
            jtxt_Rut.setText("Ej: 12345678-9");
            jtxt_Rut.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtxt_RutFocusLost

    private void jtxt_RutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_RutMousePressed
        //cuando el usuario aprieta rut se borra el ejemplo y se puede escribir en negro
        if (jtxt_Rut.getText().equals("Ej: 12345678-9")) {
            jtxt_Rut.setText("");
            jtxt_Rut.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtxt_RutMousePressed

    private void jtxt_RutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_RutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_RutActionPerformed

    private void jtxt_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cargoActionPerformed

    private void jchk_HonorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchk_HonorarioActionPerformed

        //Hace que si se da click en contrato indefinido fecha termino queda bloqueado
        boolean  TrabajadorporHonorario= jchk_Honorario.isSelected();
        this.jtxt_diaTermino.setEnabled(TrabajadorporHonorario);
        this.jtxt_agnoTerrmino.setEnabled(TrabajadorporHonorario);

        if (TrabajadorporHonorario) {
            this.jtxt_diaTermino.setText("");
            this.jtxt_mesTermino.setText("");
            this.jtxt_agnoTerrmino.setText("");
        }
    }//GEN-LAST:event_jchk_HonorarioActionPerformed

    private void jtxt_DiaInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_DiaInicioFocusLost
        if (jtxt_DiaInicio.getText().trim().isEmpty()) {
            jtxt_DiaInicio.setText("01");
            jtxt_DiaInicio.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jtxt_DiaInicioFocusLost

    private void jtxt_DiaInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_DiaInicioMousePressed
        if (jtxt_DiaInicio.getText().equals("01")) {
            jtxt_DiaInicio.setText("");
            jtxt_DiaInicio.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtxt_DiaInicioMousePressed

    private void jtxt_DiaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_DiaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_DiaInicioActionPerformed

    private void jtxt_mesInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_mesInicioFocusLost
        if (jtxt_mesInicio.getText().trim().isEmpty()) {
            jtxt_mesInicio.setText("02");
            jtxt_mesInicio.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jtxt_mesInicioFocusLost

    private void jtxt_mesInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_mesInicioMousePressed
        if (jtxt_mesInicio.getText().equals("02")) {
            jtxt_mesInicio.setText("");
            jtxt_mesInicio.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtxt_mesInicioMousePressed

    private void jtxt_mesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mesInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mesInicioActionPerformed

    private void jtxt_agnoInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_agnoInicioFocusLost
        if (jtxt_agnoInicio.getText().trim().isEmpty()) {
            jtxt_agnoInicio.setText("3333");
            jtxt_agnoInicio.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jtxt_agnoInicioFocusLost

    private void jtxt_agnoInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_agnoInicioMousePressed
        if (jtxt_agnoInicio.getText().equals("3333")) {
            jtxt_agnoInicio.setText("");
            jtxt_agnoInicio.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtxt_agnoInicioMousePressed

    private void jtxt_diaTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_diaTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_diaTerminoActionPerformed

    private void jtxt_mesTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mesTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mesTerminoActionPerformed

    private void jtxt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_direccionActionPerformed

    private void jchk_indefinidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchk_indefinidoActionPerformed
        // TODO add your handling code here:
        
        //hace que si se da click en contrato indefinido fecha termino queda bloqueado
        boolean contratoIndefinido = jchk_indefinido.isSelected();
        this.jtxt_diaTermino.setEnabled(!contratoIndefinido);
        this.jtxt_mesTermino.setEnabled(!contratoIndefinido);
        this.jtxt_agnoTerrmino.setEnabled(!contratoIndefinido);

        if (contratoIndefinido) {
            this.jtxt_diaTermino.setText("");
            this.jtxt_mesTermino.setText("");
            this.jtxt_agnoTerrmino.setText("");
        }
    }//GEN-LAST:event_jchk_indefinidoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new RegistroDePersonalPorContrato().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Actualizar;
    private javax.swing.JButton jbtn_Buscar;
    private javax.swing.JButton jbtn_Salir;
    private javax.swing.JButton jbtn_Volver;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JRadioButton jchk_Honorario;
    private javax.swing.JRadioButton jchk_indefinido;
    private javax.swing.JPanel jpan_InfoGeneral;
    private javax.swing.JTable jtbl_datosPersonal;
    private javax.swing.JButton jtbtn_agregar;
    private javax.swing.JTextField jtxt_DiaInicio;
    private javax.swing.JTextField jtxt_Nombre;
    private javax.swing.JTextField jtxt_Rut;
    private javax.swing.JTextField jtxt_agnoInicio;
    private javax.swing.JTextField jtxt_agnoTerrmino;
    private javax.swing.JTextField jtxt_cargo;
    private javax.swing.JTextField jtxt_diaTermino;
    private javax.swing.JTextField jtxt_direccion;
    private javax.swing.JTextField jtxt_fonoFijo;
    private javax.swing.JTextField jtxt_mesInicio;
    private javax.swing.JTextField jtxt_mesTermino;
    private javax.swing.JTextField jtxt_sueldo;
    private javax.swing.JTextField jtxt_tipoHorario;
    // End of variables declaration//GEN-END:variables
}
